create table invoices (
    id bigint generated by default as identity primary key,
    repair_order_id bigint not null,
    invoice_number varchar(50) not null,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null,

    constraint fk_invoice_repair_order
        foreign key (repair_order_id) references repair_orders(id),

    constraint uq_invoice_repair_order unique (repair_order_id),
    constraint uq_invoices_invoice_number unique (invoice_number)
);

create index idx_invoice_repair_order_id on invoices(repair_order_id);