create table invoice_line_items (
    id bigint generated by default as identity primary key,
    invoice_id bigint not null,
    description varchar(200) not null,
    quantity int not null,
    unit_price_cents int not null,
    created_at timestamp not null,
    updated_at timestamp not null,

    constraint fk_invoice_line_items_invoice
        foreign key (invoice_id) references invoices(id)
);

create index idx_invoice_line_items_invoice_id on invoice_line_items(invoice_id);
